name: Payment%20Services/pd-cp-appservice-tf-Preprod
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - develop
env:
  application_insight_string: InstrumentationKey=2d6a7162-53de-471c-8f04-989f091b8606;IngestionEndpoint=https://westus2-2.in.applicationinsights.azure.com/;LiveEndpoint=https://westus2.livediagnostics.monitor.azure.com/;ApplicationId=7d646443-3b94-41ff-b102-b730c330b062
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: WebAppService
      run: echo Creating WebApp
#     # This item has no matching transformer
#     - task: TerraformTaskV4@4
#       inputs:
#         provider: azurerm
#         command: init
#         commandOptions: -backend-config=resource_group_name="rg-pd-cp-d-azuw" -backend-config=storage_account_name="pdcptfstate01dev" -backend-config=container_name="tfstatepreprod" -backend-config=key="pd-cp-webapp-r-azue/terraform.tfstate"
#         backendServiceArm: Payment Dev SP
#         backendAzureRmResourceGroupName: rg-pd-cp-d-azuw
#         backendAzureRmStorageAccountName: pdcptfstate01dev
#         backendAzureRmContainerName: tfstatepreprod
#         backendAzureRmKey: pd-cp-webapp-r-azue/terraform.tfstate
#     # This item has no matching transformer
#     - task: TerraformTaskV4@4
#       inputs:
#         provider: azurerm
#         command: plan
#         commandOptions: "-var-file=terraform_r_azue.tfvars"
#         environmentServiceNameAzureRM: Payment Dev SP
