name: Migrate Azure DevOps to GitHub Actions

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up GitHub CLI and install the extension
    - name: Install GitHub CLI and gh-actions-importer extension
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get install gh
        gh extension install github/gh-actions-importer

    # Step 3: Configure GitHub Actions Importer
    - name: Configure GitHub Actions Importer
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      run: |
        gh actions-importer configure

    # Step 4: Perform dry-run migration
    - name: Dry-run migration
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
        AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
        AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
      run: |
        mkdir -p tmp/dry-run
        gh actions-importer dry-run azure-devops pipeline \
          --pipeline-id 1636 \
          --azure-devops-organization "${AZURE_DEVOPS_ORG}" \
          --azure-devops-project "${AZURE_DEVOPS_PROJECT}" \
          --output-dir tmp/dry-run

    # Step 5: Commit migrated workflows (if dry-run is successful)
    - name: Commit migrated workflows
      if: success()
      run: |
        mv tmp/dry-run/.github/workflows/* .github/workflows/
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .github/workflows/
        git commit -m "Add migrated Azure DevOps pipeline workflows"
        git push origin main
