name: Azure DevOps Migration Automation

on:
  workflow_dispatch:
    inputs:
      pipeline-id:
        description: "Azure DevOps Pipeline ID to migrate"
        required: true
        type: string

jobs:
  migrate-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Install Actions Importer Extension
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh extension install github/gh-actions-importer

    - name: Update Actions Importer Image
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh actions-importer update

    - name: Set Up Configuration Manually
      run: |
        mkdir -p ~/.gh-actions-importer
        echo "azure-devops:" > ~/.gh-actions-importer/config.yml
        echo "  org: ${{ secrets.AZURE_DEVOPS_ORG }}" >> ~/.gh-actions-importer/config.yml
        echo "  token: ${{ secrets.AZURE_DEVOPS_TOKEN }}" >> ~/.gh-actions-importer/config.yml

    - name: Dry Run Migration
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p tmp/dry-run
        gh actions-importer dry-run azure-devops pipeline \
          --pipeline-id ${{ github.event.inputs.pipeline-id }} \
          --azure-devops-organization ${{ secrets.AZURE_DEVOPS_ORG }} \
          --azure-devops-project ${{ secrets.AZURE_DEVOPS_PROJECT }} \
          --output-dir tmp/dry-run

    - name: Audit Pipeline
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p tmp/audit
        gh actions-importer audit azure-devops pipeline \
          --pipeline-id ${{ github.event.inputs.pipeline-id }} \
          --azure-devops-organization ${{ secrets.AZURE_DEVOPS_ORG }} \
          --azure-devops-project ${{ secrets.AZURE_DEVOPS_PROJECT }} \
          --output-dir tmp/audit

    - name: Upload Dry Run Results
      uses: actions/upload-artifact@v3
      with:
        name: dry-run-results
        path: tmp/dry-run

    - name: Upload Audit Results
      uses: actions/upload-artifact@v3
      with:
        name: audit-results
        path: tmp/audit
