name: Extract authors

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  extract-authors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with: 
          repository: Saideep09/branch-protection-rules
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          path: target-repo 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install git-filter-repo
        run: pip install git-filter-repo

      # Print authors BEFORE changes
      - name: Print Authors Before Rewrite
        run: |
          echo "Authors Before Rewrite:"
          git -C target-repo log --all --pretty="%an <%ae>" | sort | uniq

      - name: Generate Author Mapping
        run: |
          # Prepare author mappings dynamically
          cd target-repo
          git log --all --pretty="%an <%ae>" | sort | uniq > authors.txt
          
          # Generate mappings
          touch mappings.txt
          while IFS= read -r line; do
            old_email=$(echo "$line" | cut -d' ' -f2 | tr -d '<>')
            new_email="new_${old_email}"
            new_name="New $(echo "$line" | cut -d' ' -f1)"
            echo "$old_email $new_name <$new_email>" >> mappings.txt
          done < authors.txt
          
          # Display mappings
          echo "Author Mappings:"
          cat mappings.txt

      - name: Prepare Mailmap File
        run: |
          cd target-repo
          touch authors.txt
          while IFS= read -r line; do
            # Extract original email and name
            old_name=$(echo "$line" | cut -d' ' -f1)
            old_email=$(echo "$line" | cut -d' ' -f2 | tr -d '<>')
            
            # Generate new email and name dynamically
            new_email="new_${old_email}"
            new_name="New ${old_name}"
            
            # Write valid mailmap entry
            echo "$old_email $new_name <$new_email>" >> authors.txt
          done < authors.txt
          
          # Display the final mailmap file
          echo "Mailmap File Content:"
          cat authors.txt


      - name: Rewrite Commit History Using CLI
        run: |
          cd target-repo
          # Use git-filter-repo CLI to rewrite author info
          git-filter-repo --mailmap authors.txt --force

      - name: Push Rewritten History to Remote
        run: |
          cd target-repo
          git remote add origin https://github.com/Saideep09/branch-protection-rules.git
          git push origin --force

      # Print authors AFTER changes
      - name: Print Authors After Rewrite
        run: |
          echo "Authors After Rewrite:"
          git -C target-repo log --all --pretty="%an <%ae>" | sort | uniq

      - name: Upload Authors as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: authors-list
          path: target-repo/authors.txt
