name: Copy samw.yml File

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    # Checkout the source repository
    - name: Checkout Source Repository
      uses: actions/checkout@v4
      with:
        repository: Saideep09/seva_migration
        ref: main
        token: ${{ secrets.SOURCE_REPO_PAT }}

    # Copy the required file
    - name: Copy File
      run: |
        mkdir -p temp_folder
        cp .github/workflows/samw.yml temp_folder/

    # Persist the copied file as an artifact
    - name: Upload File as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: samw-file
        path: temp_folder/samw.yml

    # Checkout the destination repository
    - name: Checkout Destination Repository
      uses: actions/checkout@v4
      with:
        repository: Saideep09/branch-protection-rules
        ref: main
        token: ${{ secrets.DEST_REPO_PAT }}

    # Download the artifact to access the copied file
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: samw-file
        path: .github/workflows/

    # Commit and push changes to the destination repo
    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .github/workflows/samw.yml
        git commit -m "Add samw.yml copied from source repository"
        git push origin main
