name: "Onboarding Workflow"
on:
  issues:
    types: []

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue Body
        id: issue_body
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            console.log("Issue Body: ", issueBody);

            // Adjusted regular expressions to account for markdown headers (###)
            const sourceNameMatch = issueBody.match(/### Source Name\s*\n*(.*)/);
            const orgNameMatch = issueBody.match(/### Organization Name\s*\n*(.*)/);
            const additionalInfoMatch = issueBody.match(/### Additional Information\s*\n*(.*)/);

            const sourceName = sourceNameMatch ? sourceNameMatch[1].trim() : "Not provided";
            const orgName = orgNameMatch ? orgNameMatch[1].trim() : "Not provided";
            const additionalInfo = additionalInfoMatch ? additionalInfoMatch[1].trim() : "None";

            console.log("Source Name: ", sourceName);
            console.log("Org Name: ", orgName);
            console.log("Additional Info: ", additionalInfo);

            core.setOutput("source_name", sourceName);
            core.setOutput("org_name", orgName);
            core.setOutput("additional_info", additionalInfo);

      - name: Print Variables
        run: |
          echo "Source Name: ${{ steps.issue_body.outputs.source_name }}"
          echo "Org Name: ${{ steps.issue_body.outputs.org_name }}"
          echo "Additional Information: ${{ steps.issue_body.outputs.additional_info }}"
